name: jsonp
version: 2.0.0
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-jsonp
description: Read from jsonp enabled websites
dev_dependencies:
  polymer: any
