name: jsonp
version: 1.0.0
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-jsonp
description: Read from jsonp enabled websites
dependencies:
  js: any
dev_dependencies:
  polymer: any
  unittest: any
