name: jsonp
version: 0.0.2
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-jsonp
description: Read from jsonp enabled websites
dependencies:
  js: any
dev_dependencies:
  web_ui: any
