name: jsonp
version: 1.0.5
author: Matthew Franglen <matthew.franglen@gmail.com>
homepage: https://github.com/matthewfranglen/dart-jsonp
description: Read from jsonp enabled websites
dev_dependencies:
  polymer: any
  unittest: any
  mock: any
